[build]
  command = "pip install -r motorcycle_registration/requirements.txt -q"
  functions = "motorcycle_registration/netlify/functions"
  publish = "motorcycle_registration"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.12"
